### PR TITLE
Theme Support with a Dark Mode

### PR DESCRIPTION
**Pull request by dltmurphy**
This is in reference to the Dark Mode feature requests below:

[Dark Mode Feature Suggestion](https://community.bitwarden.com/t/dark-mode-for-web-vault/6790)

[Dark Mode Contribution Forum](https://community.bitwarden.com/t/web-vault-dark-mode/29756)

The options section successfully changes the theme when you select the other theme, however it doesn't save it to the account so after logging out and back in or refreshing the page, you're back to the default used by the browser

Theming in variables.scss should allow easy addition for Nord and Solarised themes that are present in the extension already

Remade from [958](https://github.com/bitwarden/web/pull/958) after misconfiguration of git

### CODE REVIEW

**Comment by dltmurphy** [comment]
Theme option is now saving correctly - I forgot to add it into the submit()

**Comment by cscharf** [comment]
Pulling PR for unit testing in review, thanks for the contribution! Will provide any feedback soon.

**Review by cscharf — COMMENTED** [review]
This is great! I'm excited for this as I'm a huge proponent of dark mode all the things! I'm not sure if you happen to have any organizations setup, but I would encourage you in your local test environment to setup at least 1 or 2 free orgs, invite another test user, create some collections, etc. as it appears some of those aspects aren't being styled. Overall looking pretty nice!

Some initial findings/feedback:

Organization view seems a little off:
image

May need some love on images that are embedded that assume a white background:
image

Subscription text is not readable due to lack of contrast, similar to collection link labels:
image

Can you tell the theme of my test orgs 😁 
image

Not sure if context/gear menus need some styling changes:
image

**Comment by dltmurphy** [comment]
Making me hungry with those org names! I'll get on with styling those sections tomorrow - I did go to make an org for testing but got side-tracked with the table lists. I aren't sure on remaking the image in dark mode but can give it a shot in gimp :-)

**Comment by dltmurphy** [comment]
@cscharf this is why i missed the organisations out:
image

Is there a way to allow it in dev or is it not possible like the premium features? I'll buy it if not

**Comment by djsmith85** [comment]
Hey @dltmurphy the dark mode looks awesome 👍 To save you from going through gimp ;) I've had a look at the images and the only one I could find missing transparency/alpha channel was `totp-countdown.png` located under `/src/images`

I've added the transparency to it and as I unfortunately can't upload it directly, I'll add it here inline.

totp-countdown

**Comment by dltmurphy** [comment]
Perfect timing @djsmith85 - I've just got to this part! Many thanks!!

I've added a CSS filter for inverting the colour and making it grayscale which looks pretty good in dark mode:

image

**Comment by dltmurphy** [comment]
I believe I've styled everything now, @cscharf. I can't get premium to work on my local dev, would you be able to test this on yours or advise how to do it?

**Comment by cscharf** [comment]
Great, thanks @dltmurphy , I'll pull it down and give it another run-through, however when I looked the only things that were off was what I added screen shots of; the premium features like TOTP generation, reports, etc. all looked good; same with file uploads/attachment lists, etc.

**Comment by whalehub** [comment]
@dltmurphy When I tried out your branch from the earlier pull request, all of the `/admin` pages were unaffected by the dark theme. Just something to keep in mind before merging this, unless that issue has already been rectified in this newer iteration.

**Comment by cscharf** [comment]
> @dltmurphy When I tried out your branch from the earlier pull request, all of the `/admin` pages were unaffected by the dark theme. Just something to keep in mind before merging this, unless that issue has already been rectified in this newer iteration.

The `/admin` pages are a different site/application, as is the business portal. That may not be applicable here, at least for this PR but opens the doorway for someone interested in tackling those web apps separately perhaps. Also, there's not really a preferences section for `/admin` in the site as they're just basic administrative server tools; same for the business portal.

**Comment by whalehub** [comment]
> Also, there's not really a preferences section for `/admin` in the site as they're just basic administrative server tools; same for the business portal.

@cscharf Good point, I hadn't considered that. I'll probably just write a [Stylus](https://github.com/openstyles/stylus) theme for that part of the application then.

**Comment by dltmurphy** [comment]
Once this PR is tested and everyone is happy for it to be merged, would the next step then be to add the theme setting to the database against the user so that it follows the user across devices? One column for the vault and one for the browser, then the admin and business portal can read the theme and present the correct styling for the user

**Comment by cscharf** [comment]
> Once this PR is tested and everyone is happy for it to be merged, would the next step then be to add the theme setting to the database against the user so that it follows the user across devices? One column for the vault and one for the browser, then the admin and business portal can read the theme and present the correct styling for the user

Once this is in, I think we'll want to keep them to the web vault alone for the time being. The business portal and admin sites are ASP.NET MVC applications vs. front-end Angular apps and use a completely different UI framework without really being attuned or setup well for theme support at the moment. Also since different themes may or may not be available across clients, we likely wouldn't want to store that in the database either; perhaps leaving it to local storage, a cookie or something like that which in the future might float the selected theme between apps for the same root domain (we'll see I guess). The web vault is the place most folks are in most of the time so it makes more sense to focus on that for the time being.

**Review by cscharf — COMMENTED** [review]
Looks good code-wise, doing another local test as I have time here this week, thanks again @dltmurphy !

**Comment by cscharf** [comment]
Okay @dltmurphy , some final nits and then I think we'll be good!

- The blue color set in the dark theme for links is too dark, skewing the contrast ratios beyond WCAG acceptable ratios (accessibility concern). This is noted in the first screen shot (1), the second being from our browser extension's dark theme (2) (and matches the mobile app's dark theme as well which shows a valid contrast ratio blue)
- The dark grey/gray text shown on some screens, such as the invoice list for an organization, is too dark and lacks enough contrast for readability (3).

---

1. Blue is too dark, not enough contrast (web vault)

image

2. Blue is "just right" (browser extension / mobile)

image

3. see `/organizations/{orgId}/settings/billing` (note, I noticed there is a lack of CSS classes assigned to a lot of these elements, so general styling changes may need refinement or new classes added and double-checked across the UI).

image

**Comment by dltmurphy** [comment]
@cscharf 

Yeah, I weren't certain on the blue so just went with the brand colour. I'll get that updated

Is the grey text okay in the first screenshot under the link for the items?
image

I'll try to look at the invoices styling. I keep getting errors popping up about not being able to do things in self hosted so can't test everything fully (not good at C# to edit the server APIs and such). I think there may be some white background in the paypal section too, can you check this for me in your environment?

**Comment by cscharf** [comment]
> Is the grey text okay in the first screenshot under the link for the items?

I think that's okay, although if it were lightened up a little bit that wouldn't hurt I don't think.

>I think there may be some white background in the paypal section too, can you check this for me in your environment?

Yes, I can't get it to load locally due to script blocks/protections (not configured for localhost at the moment), however I do see that would need special styling overrides to be supported in dark-mode [documented here](https://braintree.github.io/braintree-web-drop-in/docs/current/index.html#styling) and [described here](https://developers.braintreepayments.com/guides/drop-in/customization/javascript/v3#customize-your-ui).

I would consider PayPal or styling these types of drop-ins as `out-of-scope`, unless it's bugging you to have it done/completed... In that instance I would encourage you to setup your braintree/paypal keys with your own sandbox for local testing:

```JSON
    "globalSettings:braintree:publicKey": "--SECRET--",
    "globalSettings:braintree:production": "False",
    "globalSettings:braintree:privateKey": "--SECRET--",
    "globalSettings:braintree:merchantId": "--SECRET--",
    "globalSettings:braintree:accessToken": "access_token$sandbox$--SECRET--$--SECRET--",
```

image

**Comment by dltmurphy** [comment]
@cscharf I think i've got the contrasts sorted and the loading of the paypal section is dark now with the loading svg white. I haven't got paypal working to be able to test the form though as I'm getting an error i'm struggling to track down:
image


If Paypal works on yours could you test to see if it looks okay or not please? If the form looks bad I'll just remove the dark styling from the container and come back to it in future once i've figured it out (or someone else does)

**Review by cscharf — APPROVED** [review]
@dltmurphy , this looks good to go I believe, will let our QA team get a hold of it when they get a chance and I'll let you know if there are any questions or issues that arise. Thanks again!

**Comment by cscharf** [comment]
Hi @dltmurphy, we've gotten some feedback from the QA team and others internally and they brought up some good points. Would you be willing to make some adjustments?

* A couple of the folks thought it was too dark, but most disagreed and offered the following alternative view/reasoning:
* There's an absence of lighter grays to make foreground elements (e.g. the Vault/Manage/Tools/Settings tabs) stand out. In our other dark modes, everything that's clickable is really well delineated with lighter tones and clearly-visible borders, whereas in this implementation so far it causes some squinting
* You can’t see where UI elements end or begin very well. No contrast between things like the background of the page and the background of the app callout element or the list of options on the left. It is very flat, no depth

Hopefully that makes sense. If you take a look at the Browser Extension dark mode you'll see the contrast they're referencing, as well as grays. This is also evident in the desktop app.

The team is excited about the prospect of having a dark mode for the web vault so I'm hopeful you'll be willing to tackle this feedback. Overall everyone is looking forward to it.

**Comment by cscharf** [comment]
Also, apparently the changes to the light mode created a white background and made some other unexpected changes that I missed during my review. I'm going to revert the commit to `master` here shortly, perhaps you can re-submit with some of the feedback incorporated and I'll put it back to QA when done directly on the branch (vs. merging in) until we've finalized it.

Sorry for the confusion and thanks again for the contribution!

**Comment by cscharf** [comment]
And, in discussion with Kyle, we should be matching the color schemes from the other clients *exactly* in the web, I didn't think to check whether they were in alignment.

**Comment by dltmurphy** [comment]
Evening @cscharf. Yeah of course! I've got some time tonight and tomorrow to have a look

The background is the same as the extension #222222 I'll do the lighter greys and links the same so I'll add in the same #363636 for the foreground and update the link colour to be #52bdfb like the below?

image
image

Where was the white background being added on the light version? I copied the same colours into the variables as what was already set so I'll have called the wrong variable somewhere in the styles

**Comment by cscharf** [comment]
Awesome, thanks!

> The background is the same as the extension #222222 I'll do the lighter greys and links the same so I'll add in the same #363636 for the foreground and update the link colour to be #52bdfb like the below?

I believe so, that looks much better I believe, but I'm going to CC a few more folks on here to take a quick look.

> Where was the white background being added on the light version?

One of the areas was the list of users for an org when invited/accepted/confirmed in the list; Previous to the changes in this PR, the background of the web vault was a soft grey. Now the background is super white.

Also, some initial things the team found that I had missed and may or may not be handled with the changes you're making now:

1. When you login with an account that has 2FA enabled, you are taken to a screen to enter your auth code. On that prompt there is a Cancel button,  when looking at Dark Mode, the cancel button is not styled properly (see screenshot attached)
2. The Billing content font is a dark grey. Should be lighter color for ease of visibility. Screenshot attached.
3. The Event Logs table font is a dark grey until user hovers over the content. Should be lighter color for ease of visibility. Screenshot attached.
4. When NOT on dark mode, the copy within the call to action buttons are not visible (see screenshot attached).
5. When creating/viewing/editing a Login item, the block next to the Authenticator Key is super black and looks odd against the dark mode background (see screenshot attached)
6. When logging in to the web vault, there is a small key icon. When in Dark Mode that key is so dark that you can't really see it
7. When creating a new login item on a smaller window size (forcing a vertical scroll in the modal), the scroll bar has not been adjusted to match the dark mode
8. When viewing an item in Dark Mode, the Favorite icon at the bottom is hard to see since it is just an outline in a darker blue color

image
image
image
image
image
image
image
image


@fschillingeriv , @vincentsalucci , @theegreatsamboni , FYI ☝🏻

**Comment by theegreatsamboni** [comment]
Thanks for taking a look at these changes so quickly @dltmurphy!
Re: white vs grey background, I'll attach a screenshot where you can see the difference pretty clear. Login/create new background is the soft grey in production (right) vs. all white from the PR (left)

Let me know if you have any other questions! 
Screen Shot 2021-06-03 at 2 13 15 PM

**Comment by dltmurphy** [comment]
Ah, I had missed layout_frontend as being a different colour, added that back in now @theegreatsamboni. I think it should fix the button text not appearing, I'll test it tomorrow on my other PC that has bypassed the selfhosted restriction
image

@cscharf the table text colours are done and i've made the favourite icon the same colour as the links 
image

I'm not sure on the key icon or the OTP section. Which browser are you testing in? I've tried chrome, edge and firefox and i don't get a key and the OTP looks right:
image

I've just noticed on the light theme I've also changed the secondary buttons to be blue on hover so i'll fix this too. I'll push what i've done so far if you can check those bits are working for you?

**Comment by cscharf** [comment]
> I'm not sure on the key icon

I saw it in Brave, using Brave's dark mode.

**Comment by dltmurphy** [comment]
Hey @cscharf

Would you be able to have a look at the latest version [here](https://github.com/dltmurphy/web) and see if you're happy with it?

I've just got Brave installed with multiple passwords against vault.bitwarden.com but i only get a key in the address bar at the top so I'm not sure on that one

**Comment by cscharf** [comment]
@dltmurphy , thank you, can you please submit another PR and I'll have a few folks internally review from there.

**Comment by STaRDoGG** [comment]
Did @djsmith85 's transparent totp image get merged? I need it for my nord theme as well. Tested it locally and it works.

**Comment by dltmurphy** [comment]
@STaRDoGG not yet, we had to revert it as there were bits of styling I missed in Light theme. Hopefully it should get reviewed next week by the design team, depending on how busy they are with the upcoming release

**Pull request merged**
