### PR TITLE
Run npm lint in CI

### PR DESCRIPTION
**Pull request by Hinton**
## Type of change
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [x] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

Adds `npm run lint` to the CI pipeline. This will ensure the code passes linting before merging.

## Before you submit
- [ ] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [x] This change has particular **deployment requirements** (notify the DevOps team)

### CODE REVIEW

**Review by mimartin12 — COMMENTED** [review]
Github actions looks good 👍

**Review by cscharf — CHANGES_REQUESTED** [review]
Just need to address the following issue during the build:

https://github.com/bitwarden/web/runs/4313630205?check_suite_focus=true#step:11:11

**Comment by mimartin12** [comment]
> Just need to address the following issue during the build:
> 
> https://github.com/bitwarden/web/runs/4313630205?check_suite_focus=true#step:11:11

Hey @cscharf  I think that this is related to this line in the `organization-plans.components.ts` file.

https://github.com/bitwarden/web/blob/cbf65c5f428544290870cc320b750b9927ee9eef/src/app/settings/organization-plans.component.ts#L254

@Hinton would you take a look when you get a chance? Let me know if there is anything I can do.

**Comment by Hinton** [comment]
Should be fixed now. I intentionally left it behind just to verify the action would fail, didn't expect it to be reviewed that quickly 😀

**Review by cscharf — APPROVED** [review]

**Pull request merged**
