### PR TITLE
add lang to HTML page

### PR DESCRIPTION
**Pull request by coliff**
## Type of change

- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

Fixes an accessibility issue:
https://googlechrome.github.io/lighthouse/viewer/?psiurl=https%3A%2F%2Fvault.bitwarden.com%2F%23%2F&strategy=desktop&category=performance&category=accessibility&category=best-practices&category=seo

REF: https://web.dev/html-has-lang/?utm_source=lighthouse&utm_medium=lr

## Code changes

Adds `lang="en"` so the language is defined.

## Before you submit

- [ ] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

### CODE REVIEW

**Comment by Hinton** [comment]
Lang is not always English though. We would need a way to on the fly replace the language should a user have picked something different.

**Comment by coliff** [comment]
ah sorry then - I didn't realise it was localized. Feel free to close then unless there's a way to set this automatically based on the set language.

**Comment by dltmurphy** [comment]
@Hinton Would the below work in `services.module.ts` underneath the locale class on line 88?

`htmlEl.setAttribute("lang", i18nService.translationLocale);`

**Comment by Hinton** [comment]
@dltmurphy Yea, that would do the trick I think. We would want to do the same change to each of our clients though. And also make sure that it gets outputed in the correct subtag (https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry). (I suspect language variants would need some aligning to fit properly.)

**Comment by djsmith85** [comment]
@coliff Thank you for the contribution. 

Based on the feedback from @dltmurphy and @Hinton is this something you'd like to tackle, or would you rather close this?

**Comment by coliff** [comment]
I think this should be fixed, but I'm not familiar with TypeScript so can't take this on myself. Could someone else do this? Or would it be better to add a GitHub Issue for it and close this PR?

**Comment by Hinton** [comment]
HI @coliff,

Since we will be migrating to a mono repository we most likely won't have time to resolve this before. But I've created a ticket to keep this tracked and hopefully we can get around to it shortly. https://github.com/bitwarden/web/issues/1625

**Pull request closed without merging**
