### PR TITLE
Add link to Firefox addon

### PR DESCRIPTION
**Pull request by bbrks**

### CODE REVIEW

**Comment by kspearrin** [comment]
Can you change the link to

https://addons.mozilla.org/firefox/addon/bitwarden-password-manager/

so that it doesn't force the `en-US` version on everyone?

**Comment by bbrks** [comment]
Whoops, didn't catch that. Thanks! I'll update later.

**Comment by bbrks** [comment]
@kspearrin In the same vein, I've de-localised the iTunes app store link too.

**Comment by kspearrin** [comment]
Thanks

**Pull request merged**
