### PR TITLE
Checkbox and site icons vertical alignment

### PR DESCRIPTION
**Pull request by SrdjanMilic**
Check box elements in general, and site icons in `"My Vault"` page view, were not properly aligned.  
Setting up the `line-height: 0;` on few elements fix those issues. Also, check box and label `Remember me` at login(and probably else where) are fixed as well.

### CODE REVIEW

**Comment by kspearrin** [comment]
You have lots of other changes in this PR that are unrelated to the line height adjustment. Please remove those and we can consider merging.

**Comment by SrdjanMilic** [comment]
Really sorry. I've made a mess. Those are my first PR, although I work with git for a while now.  

1. I've one PR from yesterday. I've missed out to create a new branch, so the changes are from my master branch. Please take a look. Doesn't good. I know.  
2. Today, I've created a new branch for another PR, but I missed out that there are changes from yesterday included, so I ended up in this situation.  

Could you please, help me out to resolve this mess. I am not sure how to remove those files, as they will be removed from previous PR(as I can understand) if I delete them using this page: [https://github.com/bitwarden/web/pull/522/files](https://github.com/bitwarden/web/pull/522/files)

I realize that those files should be deleted from `vertical-align` branch only, and that will do no harm on merging process hopefully. Pleases confirm.  

Would it be better to start all over again, delete all of the two PR and create a new ones properly, or there is a way to fix this in another manner?

Thank you, and sorry once again.

**Comment by kspearrin** [comment]
I'd recommend just starting over. Create your feature branch off of master.

**Comment by SrdjanMilic** [comment]
OK. I've started from scratch and already created the first pull request.  
Should I just close the old ones? I rather want to delete them, but I can't see any options for doing so.

**Pull request closed without merging**
