### PR TITLE
Add locale info for hint equals password

### PR DESCRIPTION
**Pull request by cwille97**

### CODE REVIEW

**Review by cscharf — APPROVED** [review]

**Review by dmcfaddengalway — DISMISSED** [review]
Great!

**Review by cscharf — DISMISSED** [review]
Great, thanks!

**Comment by cscharf** [comment]
@cwille97, Can you please help resolve these conflicts and I'll re-approve?

**Comment by cwille97** [comment]
@cscharf I fixed the merge conflict, however the CLAassistant seems to be complaining about the license. It's showing my name twice, and I just signed it so I'm not sure what the problem is. Did I do something wrong with that?

**Comment by eliykat** [comment]
It may be because you've used 2 different email addresses:
```git
commit 8547aacc2db6f7c1617c048fa33c4e135add9931 (HEAD -> hintLocale, origin/hintLocale)
Merge: 8eebc845 1ea8762e
Author: cwille97 <cjwille@pm.me>
Date:   Mon Mar 22 19:04:22 2021 -0400

    Merge branch 'master' into hintLocale

commit 9e5a53c99dccfc4bbef366246299d0e601bf19f2
Author: Cedric Wille <cjwille@gmail.com>
Date:   Wed Nov 11 17:13:24 2020 -0500

    Add locale info for hint equals password
```

Check that both email addresses are added to your Github account, and then get the CLAassistant to re-check. (See the info and links in the CLAassistant comment above)

**Review by dmcfaddengalway — APPROVED** [review]

**Comment by cwille97** [comment]
Ah, I had just pulled off my old email I guess I'll add it back real quick to sign this, and once this is merged I can hopefully delete it again.

**Comment by cwille97** [comment]
@dmcfaddengalway @cscharf Looks like the email issue is fixed now. Let me know if there's any other issues blocking the merge.

**Review by cscharf — APPROVED** [review]
Awesome, thanks!

**Pull request merged**
